services:
  ? adp-test-aa1
  : build:
      target: development
    image: adp-test-aa1-development
    container_name: adp-test-aa1-test
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./Adp.Test.Aa1.sln:/home/dotnet/Adp.Test.Aa1.sln
      - ./src/Adp.Test.Aa1.Core:/home/dotnet/src/Adp.Test.Aa1.Core
      - ./test/Adp.Test.Aa1.Core.Tests:/home/dotnet/test/Adp.Test.Aa1.Core.Tests
      - ./src/Adp.Test.Aa1.Api:/home/dotnet/src/Adp.Test.Aa1.Api
      - ./test/Adp.Test.Aa1.Api.Tests:/home/dotnet/test/Adp.Test.Aa1.Api.Tests
      - ./test/Adp.Test.Aa1.Api.Tests/test-output:/home/dotnet/test/Adp.Test.Aa1.Api.Tests/test-output
      - ./test/Adp.Test.Aa1.Core.Tests/test-output:/home/dotnet/test/Adp.Test.Aa1.Core.Tests/test-output
