services:
  ? adp-test-aa1
  : build:
      context: .
      target: production
    image: adp-test-aa1
    container_name: adp-test-aa1
    environment:
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APPINSIGHTS_CLOUDROLE: adp-test-aa1-local