{{- include "adp-helm-library.deployment" (list . "adp-test-aa1.deployment") -}}
{{- define "adp-test-aa1.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "adp-test-aa1.container") }}
      volumes:
      - name: {{ .Values.volumeMounts.name }}
        emptyDir: {}
{{- end -}}
